### ISSUE TITLE
Infografia _ Kevin Andrew Osorio

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Kevinosorio77#1]
[Infografia_Kevin Osorio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Kevinosorio77/files/14727282/Infografia_Kevin.Osorio.pdf)

**Comment by SandyMarissaGs** [comment]
De acuerdo a la rúbrica obtuviste 19 %

**Comment by josealfredo79** [comment]
Falta agregar mas inforomacion..por favor @Kevinosorio77 y ser mas objetivo en la evaluacion @SandyMarissaGs
